'use strict';

angular.module('anorakApp')
  .filter('languagefilter', function ($translate) {
    return function (input) {
      if (input[$translate.use()]) {
        return input[$translate.use()];
      } else {
        // english is always available because generated by google translate
        return input.en;
      }
    };
  });
